/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.0   2019-11-06
*/
#include "stm32f4xx.h"
#include "FreeRTOS.h"
#include "task.h"
#include "queue.h"
#include "semphr.h"
#include "defGPIO.h"
#include "encoder.h"
#include "declarations.h"
#include "aTaskSonicSensor.h"
#include "aTaskServoMotor.h"
#include "aTaskEncoder.h"



static void prvSetupHardware(void);
static void prvSetupHardware(void);

void vATaskFunction( void *pvParameters );
void vApplicationTickHook( void );
void vApplicationTickHook( void );
void vATaskFunction( void *pvParameters );



int main(void)
{
  int i = 0;

	// Hardware configuration
	prvSetupHardware();

	//create tasks
	xTaskCreate( vSonicSensor, "sonic", 100, NULL, 2, &xSonicSensor );
	xTaskCreate( vServoMotor, "servo", 100, NULL, 2, &xServoMotor );
	xTaskCreate( vEncoder, "encoder", 100, NULL, 2, &xEncoder );

	// Start the scheduler
	vTaskStartScheduler();

  /* Infinite loop */
  while (1)
  {
	i++;
  }
}



static void prvSetupHardware(void)
{
	GPIO_InitializeAll();     //init GPIO
	Encoder_Init();           //init Encoder
	HC_SR04_Init();           //init sonic sensor

}



void vApplicationTickHook( void )
{

}
